export const mockProducts = [
  {
    id: '1',
    productName: 'Elizabeth Collar Pet Grooming Shield',
    productId: 'PET-001',
    category: ['Pet Accessories', 'Dog Supplies'],
    alibabaIds: ['ALI-12345', 'ALI-67890'],
    iconUrl: 'https://via.placeholder.com/50',
  },
  {
    id: '2',
    productName: 'High Quality Wholesale Pet Dog Toys',
    productId: 'PET-002',
    category: ['Pet Toys', 'Dog Supplies'],
    alibabaIds: ['ALI-23456'],
    iconUrl: 'https://via.placeholder.com/50',
  },
  {
    id: '3',
    productName: 'Waterproof Foldable Seat Protector',
    productId: 'PET-003',
    category: ['Pet Accessories', 'Car Accessories'],
    alibabaIds: ['ALI-34567', 'ALI-45678'],
    iconUrl: 'https://via.placeholder.com/50',
  },
  {
    id: '4',
    productName: 'Pet Water Dispenser Automatic',
    productId: 'PET-004',
    category: ['Pet Feeders', 'Cat Supplies'],
    alibabaIds: ['ALI-56789'],
    iconUrl: 'https://via.placeholder.com/50',
  },
  {
    id: '5',
    productName: 'Pet plush toy simulation duck',
    productId: 'PET-005',
    category: ['Pet Toys', 'Dog Supplies'],
    alibabaIds: ['ALI-67890'],
    iconUrl: 'https://via.placeholder.com/50',
  },
  // Add more mock products to test scrolling
  {
    id: '6',
    productName: 'Durable Plush Eggplant Cat Chew Toy',
    productId: 'PET-006',
    category: ['Pet Toys', 'Cat Supplies'],
    alibabaIds: ['ALI-78901'],
    iconUrl: 'https://via.placeholder.com/50',
  },
  {
    id: '7',
    productName: 'USB Interactive Cat Toys Laser Pen',
    productId: 'PET-007',
    category: ['Pet Toys', 'Cat Supplies'],
    alibabaIds: ['ALI-89012'],
    iconUrl: 'https://via.placeholder.com/50',
  },
  {
    id: '8',
    productName: 'Stainless Steel Blade Free Nail Clipper',
    productId: 'PET-008',
    category: ['Pet Grooming', 'Dog Supplies'],
    alibabaIds: ['ALI-90123'],
    iconUrl: 'https://via.placeholder.com/50',
  },
  {
    id: '9',
    productName: 'Stainless Steel Blade Free Nail Clipper',
    productId: 'PET-008',
    category: ['Pet Grooming', 'Dog Supplies'],
    alibabaIds: ['ALI-90123'],
    iconUrl: 'https://via.placeholder.com/50',
  },
];
